import { BankRegistration } from '../data/records';

/**
 * Builds a small one-page "Registration Certificate" PDF for a bank, in memory.
 * (Mock document for the demo. In real life the backend would return the PDF bytes.)
 *
 * A PDF is a list of numbered objects plus a cross-reference table with each
 * object's byte offset. We only need text, so the built-in Helvetica fonts are enough.
 */
export function buildCertificatePdf(r: BankRegistration): Uint8Array {
  const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
  const line = (font: 'F1' | 'F2', size: number, x: number, y: number, text: string) =>
    `BT /${font} ${size} Tf ${x} ${y} Td (${esc(text)}) Tj ET`;

  const content = [
    // Blue frame and header band
    '0.12 0.23 0.54 RG 3 w 30 30 535 782 re S',
    '0.12 0.23 0.54 rg 30 742 535 70 re f',
    '1 1 1 rg',
    line('F2', 20, 60, 770, 'DEPOSIT INSURANCE - REGISTRATION CERTIFICATE'),
    '0.1 0.1 0.1 rg',
    line('F1', 12, 60, 690, 'This is to certify that'),
    line('F2', 22, 60, 655, r.bankName),
    line('F1', 12, 60, 620, `of ${r.state} is registered as an insured bank under the Deposit Insurance scheme.`),
    line('F2', 12, 60, 570, 'Registration No.'),
    line('F1', 12, 220, 570, r.regNo),
    line('F2', 12, 60, 545, 'Reference'),
    line('F1', 12, 220, 545, r.id),
    line('F2', 12, 60, 520, 'Application date'),
    line('F1', 12, 220, 520, r.submittedOn),
    line('F2', 12, 60, 495, 'Status'),
    line('F1', 12, 220, 495, r.status),
    '0.5 0.5 0.5 rg',
    line('F1', 10, 60, 80, 'Generated by the Bank Registration Cell module (demo document, not a legal certificate).'),
  ].join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>',
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((body, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xrefAt = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  pdf += offsets.map((o) => `${String(o).padStart(10, '0')} 00000 n \n`).join('');
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF`;

  // Only ASCII characters are used, so 1 character = 1 byte and the offsets above are exact.
  return new TextEncoder().encode(pdf);
}
